apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: --ticketing
deploy:
  kubectl:
    manifests:
    - ./infra/k8s/*
    - ./infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
  - image: hoangtrx/ticketing_auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
  - image: hoangtrx/ticketing_client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: '**/*.js'
        dest: .
  - image: hoangtrx/ticketing_tickets
    context: tickets
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
  - image: hoangtrx/ticketing_orders
    context: orders
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
  - image: hoangtrx/ticketing_expiration
    context: expiration
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
  - image: hoangtrx/ticketing_payments
    context: payments
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
